server: 
 port: 8888
spring: 
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ohs?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  username: root
  password: jiangjie1
 jpa: 
  hibernate: 
   ddl-auto: update
  show-sql: true
  database: MYSQL
  properties: 
   hibernate: 
    dialect: org.hibernate.dialect.MySQL5Dialect
 thymeleaf:
  prefix: 
   classpath: static/
security: 
 basic: 
  enabled: false
  
logging: 
 level: 
  root: debug
 path: /usr/ohs/logs/
 file: ohs_log.log
  

  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiangjie.ohs.entity 